module.exports = {
  docs: {
    stook: [
      'stook/intro',
      'stook/quick-start',
      'stook/share-state',
      'stook/custom-hooks',
      'stook/use-store',
      'stook/mutate',
      'stook/get-state',
      'stook/typescript',
      'stook/test',
      'stook/faq',
    ],

    'stook-devtools': ['devtools/intro'],

    'stook-rest': [
      'rest/intro',
      'rest/quick-start',
      'rest/config',
      'rest/useFetch',
      'rest/useUpdate',
      'rest/dependent',
      'rest/share-state',
      'rest/custom-hooks',
      'rest/fetch',
      'rest/refetch',
      'rest/middleware',
    ],
    'stook-graphql': [
      'graphql/intro',
      'graphql/quick-start',
      'graphql/config',
      'graphql/useQuery',
      'graphql/useMutate',
      'graphql/query',
      'graphql/middleware',
    ],
    'stook-form': [
      'form/intro',
      'form/quick-start',
      'form/array',
      'form/nested-object',
      'form/validation',
      'form/async-validation',
      'form/error-message',
      'form/antd',
    ],
  },
}
